name: Backend CI - Tests

on:
  push: {}
  pull_request: {}

jobs:
  test-backend:
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Print Node and npm versions
        run: |
          node --version
          npm --version
        working-directory: backend

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run backend tests
        working-directory: backend
        env:
          CI: true
          JWT_SECRET: test_secret_for_ci
        run: npm test
